Changed {whattext,wstart,wstop} to auto-detect wpub location from their real dirname.

diff --git a/whattext b/whattext
--- a/whattext
+++ b/whattext
@@ -1,7 +1,12 @@
 #!/bin/bash
-if [ "$wpub" == "" ]; then
-  . /etc/freedom.conf
+
+DIRNAME=`dirname "$0"`
+REAL_DIRNAME=`cd "$DIRNAME" 1> /dev/null 2>&1 && pwd`
+if [ -z "$REAL_DIRNAME" ]; then
+    echo "Could not get real dir name from '$0'."
+    exit 1
 fi
+export wpub=$REAL_DIRNAME
 
 shopt -s nullglob
 
diff --git a/wstart b/wstart
--- a/wstart
+++ b/wstart
@@ -1,16 +1,22 @@
 #!/bin/bash
-if [ "$freedom_context" == "" ]; then
-  . /etc/freedom.conf
-   wchoose -b
-fi
 
-if [ -z "$wpub" ]; then
-    echo "Warning: wpub is not set. Exiting now !"
-    exit 0
+DIRNAME=`dirname "$0"`
+REAL_DIRNAME=`cd "$DIRNAME" 1> /dev/null 2>&1 && pwd`
+if [ -z "$REAL_DIRNAME" ]; then
+    echo "Could not get real dir name from '$0'."
+    exit 1
 fi
+export wpub=$REAL_DIRNAME
+
+core_environment="$wpub/programs/core_environment"
+if [ ! -x "$core_environment" ]; then
+    echo "'$core_environment' not found or not executable."
+    exit 1
+fi
+. "$core_environment"
 
 if [ -f $wpub/maintenance.lock ]; then
-    /bin/rm $wpub/maintenance.lock
+    rm $wpub/maintenance.lock
 fi
 
 # link images file to be used in several applications
diff --git a/wstop b/wstop
--- a/wstop
+++ b/wstop
@@ -1,18 +1,13 @@
 #!/bin/bash
 
-if [ "$freedom_context" == "" ]; then
-  . /etc/freedom.conf
-  if [ ! -f "$wpub/context/default/dbaccess.php" ]; then
-    # not initialized yet
-    exit 0
-   fi
-   wchoose -b
+DIRNAME=`dirname "$0"`
+REAL_DIRNAME=`cd "$DIRNAME" 1> /dev/null 2>&1 && pwd`
+if [ -z "$REAL_DIRNAME" ]; then
+    echo "Could not get real dir name from '$0'."
+    exit 1
 fi
-
-if [ -z "$wpub" ]; then
-    echo "Warning: wpub is not set. Exiting now !"
-    exit 0
-fi
+export wpub=$REAL_DIRNAME
 
 touch $wpub/maintenance.lock
+
 echo "check update needed ($wpub/wcheck)"
