Moved datestyle's initialization from FDL_post to CORE_post (closes #2945)
Also:
- Changed Session->last_seen date's format to ISO.

diff --git a/App/Core/CORE_post b/App/Core/CORE_post
--- a/App/Core/CORE_post
+++ b/App/Core/CORE_post
@@ -70,6 +70,22 @@ if [ "$1" = "I" ] ; then
     "$wpub"/wsh.php --api=updateclass --dbcoord="service='$pgservice_core'" --class=Session
 
     "$wpub"/wsh.php  --api=appadmin --appname=CORE
+
+    log "Setting database date locale..."
+    LCDATE=`"$wpub"/wsh.php --api=get_param --param=CORE_LCDATE| cut -f1 -d" "`
+
+    if [ "$LCDATE" = "iso" ]; then
+	PGDATESTYLE='ISO, DMY'
+    else
+	PGDATESTYLE='SQL, DMY'
+    fi
+    DATABASE=`PGSERVICE="$pgservice_core" psql -At -c "SELECT current_database();" 2> /dev/null`
+    PGSERVICE="$pgservice_freedom" psql -c "ALTER DATABASE \"$DATABASE\" SET DateStyle='$PGDATESTYLE';" #2> /dev/null
+    RET=$?
+    if [ $RET -ne 0 ]; then
+	echo "An error occured while setting DateStyle to '$PGDATESTYLE'"
+	exit $RET
+    fi
 fi
 
 
